[workflow]
workflow_schedule_interval = "@daily"
sequential_queue = "sequential"
default_queue = "general"

[aws]
bucket = "de300spring2024-billyin"
data_key = "heart_disease.csv"
p2_data_folder = "steps_data/p2"
merge_data_folder = "steps_data/merge"
merge_1 = "merge_step_1.py"
merge_2 = "merge_step_2.py"
p2_1 = "p2_step_1.py"
p2_2 = "p2_step_2.py"
cluster_emr = "j-2QP6PP3HGN9XC"
cluster_emr_merge = "j-XH79FJ3V1KZP"


[ml]
test_ratio = 0.1
outliers_std_factor = 3
labels = "Wine"
tolerance = 0.01
perturbation_std = 1.2
max_perturbation_iterations = 50
confidence_level = 0.95
