[workflow]
workflow_schedule_interval = "@daily"
sequential_queue = "sequential"
default_queue = "general"

[db]
db_identifier = "billyin-lab8-db"
db_connection = "AIRFLOW_CONN_AWS_RDS_POSTGRES"
username = 'pgde300'
password = 'de300spring2024'
host = 'postgres'
port = '5432'  # Default port for PostgreSQL
default_db = 'postgres'  # Default database you can connect to
db_name = 'demo_wine'
db_alchemy_driver = "postgresql+psycopg2"

[files]
s3_bucket = "s3://de300spring2024"
s3_file_key = "billyin_airflow_lab8/wine.csv"


[ml]
train_test_ratio = 0.2
outliers_std_factor = 3
labels = "Wine"
tolerance = 0.01
perturbation_std = 1.2
max_perturbation_iterations = 50
confidence_level = 0.95
